[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/users/test"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NIXPACKS_JDK_VERSION = "17"
MAVEN_ARGS = "clean package -DskipTests"